"""preferences schema: working/versions/pointers/deadlines

Revision ID: f07e81483ae2
Revises: 2c8e35cc16e3
Create Date: 2025-10-29 15:17:44.879661

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f07e81483ae2"
down_revision: Union[str, Sequence[str], None] = "2c8e35cc16e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "preferences_deadlines",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("deadline_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("org_timezone", sa.String(length=64), server_default="Europe/Warsaw", nullable=False),
        sa.CheckConstraint("month >= 1 AND month <= 12", name="ck_deadline_month_range"),
        sa.CheckConstraint("year >= 1900 AND year <= 2100", name="ck_deadline_year_range"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("year", "month", name="uq_deadline_period"),
    )
    op.create_table(
        "preferences_versions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("doctor_id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), server_default="checkpoint", nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=False),
        sa.Column("created_by_role", sa.String(length=16), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.CheckConstraint("month >= 1 AND month <= 12", name="ck_versions_month_range"),
        sa.CheckConstraint("year >= 1900 AND year <= 2100", name="ck_versions_year_range"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_preferences_versions_doctor_id"), "preferences_versions", ["doctor_id"], unique=False)
    op.create_index(op.f("ix_preferences_versions_month"), "preferences_versions", ["month"], unique=False)
    op.create_index(op.f("ix_preferences_versions_year"), "preferences_versions", ["year"], unique=False)

    op.create_table(
        "preferences_working",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("doctor_id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("lock_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("unavailable_duty_days", sa.JSON(), nullable=True),
        sa.Column("unavailable_oncall_days", sa.JSON(), nullable=True),
        sa.Column("preferred_duty_days", sa.JSON(), nullable=True),
        sa.Column("preferred_oncall_days", sa.JSON(), nullable=True),
        sa.Column("min_duties_weekdays", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_duties_weekdays", sa.Integer(), nullable=True),
        sa.Column("min_duties_weekends", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_duties_weekends", sa.Integer(), nullable=True),
        sa.Column("min_oncall_weekdays", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_oncall_weekdays", sa.Integer(), nullable=True),
        sa.Column("min_oncall_weekends", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_oncall_weekends", sa.Integer(), nullable=True),
        sa.Column("weekend_back_to_back_allowed", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("preferred_partners", sa.JSON(), nullable=True),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.Column("last_saved_at", sa.DateTime(), nullable=True),
        sa.Column("last_saved_by_user_id", sa.Integer(), nullable=True),
        sa.Column("last_saved_by_role", sa.String(length=32), nullable=True),
        sa.Column("last_admin_note", sa.Text(), nullable=True),
        sa.CheckConstraint("month >= 1 AND month <= 12", name="ck_working_month_range"),
        sa.CheckConstraint("year >= 1900 AND year <= 2100", name="ck_working_year_range"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("doctor_id", "year", "month", name="uq_working_doctor_period"),
    )
    op.create_index(op.f("ix_preferences_working_doctor_id"), "preferences_working", ["doctor_id"], unique=False)
    op.create_table(
        "preferences_pointers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("doctor_id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("current_checkpoint_id", sa.String(length=64), nullable=True),
        sa.Column("submitted_at", sa.DateTime(), nullable=True),
        sa.Column("submitted_by_user_id", sa.Integer(), nullable=True),
        sa.Column("submitted_by_role", sa.String(length=16), nullable=True),
        sa.CheckConstraint("month >= 1 AND month <= 12", name="ck_pointer_month_range"),
        sa.CheckConstraint("year >= 1900 AND year <= 2100", name="ck_pointer_year_range"),
        sa.ForeignKeyConstraint(
            ["current_checkpoint_id"],
            ["preferences_versions.version_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("doctor_id", "year", "month", name="uq_pointer_doctor_period"),
    )
    op.create_index(op.f("ix_preferences_pointers_doctor_id"), "preferences_pointers", ["doctor_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_preferences_pointers_doctor_id"), table_name="preferences_pointers")
    op.drop_table("preferences_pointers")
    op.drop_index(op.f("ix_preferences_working_doctor_id"), table_name="preferences_working")
    op.drop_table("preferences_working")
    op.drop_index(op.f("ix_preferences_versions_year"), table_name="preferences_versions")
    op.drop_index(op.f("ix_preferences_versions_month"), table_name="preferences_versions")
    op.drop_index(op.f("ix_preferences_versions_doctor_id"), table_name="preferences_versions")
    op.drop_table("preferences_versions")
    op.drop_table("preferences_deadlines")
    # ### end Alembic commands ###
