"""create doctors table

Revision ID: f9b85acfa964
Revises:
Create Date: 2025-10-27 14:37:25.884500

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f9b85acfa964"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "doctors",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("role", sa.Enum("specialist", "resident", name="doctor_role"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("is_head", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="uq_doctors_email"),
    )
    op.create_index(op.f("ix_doctors_first_name"), "doctors", ["first_name"], unique=False)
    op.create_index(op.f("ix_doctors_last_name"), "doctors", ["last_name"], unique=False)
    op.create_index("ix_doctors_last_name_role", "doctors", ["last_name", "role"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_doctors_last_name_role", table_name="doctors")
    op.drop_index(op.f("ix_doctors_last_name"), table_name="doctors")
    op.drop_index(op.f("ix_doctors_first_name"), table_name="doctors")
    op.drop_table("doctors")
    # ### end Alembic commands ###
